server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql_WDx6e8
    url: jdbc:mysql://192.168.10.101:3306/poetry?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lxxx.poetrybackend: debug


elasticsearch:
  serverUrl: 192.168.10.101:9200
  apiKey: MFlzVFI0NEIyTGZUM01VRHlCelk6allFYlpKUUhUTFdCLW9OTVdjeWwyQQ==